workflows:
  debug_ios_build:
    name: Debug iOS Build
    max_build_duration: 60
    environment:
      flutter: "3.23.1"
      xcode: "15.4"        # هادي هي النسخة المستقرة دابا فـ 2026
      cocoapods: default
    scripts:
      - name: Install Flutter dependencies & Pods
        script: |
          flutter clean
          flutter pub get
          cd ios
          # مسح أي بقايا قديمة باش ما يوقعش Conflict
          rm -rf Pods
          rm -f Podfile.lock
          pod install --repo-update
          cd ..
      - name: Build Debug IPA
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app