workflows:
  ios-debug-build:
    name: iOS Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable      # هادي غاتهنيك، غايجيب آخر نسخة مستقرة (3.24 أو 3.27...)
      xcode: latest        # باش يخدم مع Firebase و Swift الجديد
      cocoapods: default
scripts:
  - name: Install Flutter dependencies & Pods
    script: |
      flutter clean
      flutter pub get
      cd ios
      pod deintegrate
      pod install --repo-update
      cd ..
  - name: Build Debug IPA
    script: |
      flutter build ipa --debug --no-codesign
artifacts:
  - build/ios/ipa/*.ipa