platform :ios, '13.0'

# هاد السطر كيقول ليه: "حاول تقرا الملف، وإلا مالقيتيهش ما ديرش Error"
podhelper_path = File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'podhelper.rb')
if File.exist?(podhelper_path)
  load podhelper_path
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # تأكد أن هاد الدالة كاينة عاد خدم بها
  if defined?(flutter_install_all_ios_pods)
    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target) if defined?(flutter_additional_ios_build_settings)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end